layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: aj.bolt.3
  hackerrank: adrian_jc_bolt
  instagram: bolt_aj
  # keybase: your_username
  linkedin: adrian-bolt-488b8340
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 3741089
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  vk: ajbolt
  # website: http://your_website_url
  youtube: channel/UCi69OT9wiX9ddD6UGNBQZSg

topics:
  - name: Rust
    web_url: https://www.rust-lang.org
    image_url: https://rustacean.net/assets/rustacean-orig-noshadow.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://cdn-images-1.medium.com/max/1200/1*iDQvKoz7gGHc6YXqvqWWZQ.png
 

  - name: Quantum Computing
    web_url: https://github.com/topics/quantum-computing
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Bloch_sphere.svg/963px-Bloch_sphere.svg.png
